// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-tP91F4XOt0Jo-HUcgGxl3195hvzJM-4',
    appId: '1:551175519868:web:3fe8a05c46700fbc7b13f9',
    messagingSenderId: '551175519868',
    projectId: 'my-first-firebase-efee1',
    authDomain: 'my-first-firebase-efee1.firebaseapp.com',
    storageBucket: 'my-first-firebase-efee1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiUUpCJo_OCUvHqUXSzkgWcywSn8RKIak',
    appId: '1:551175519868:android:bc758f118156492f7b13f9',
    messagingSenderId: '551175519868',
    projectId: 'my-first-firebase-efee1',
    storageBucket: 'my-first-firebase-efee1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvAUoN7aOBhX9z582W6UL8KWYVm5RRY7s',
    appId: '1:551175519868:ios:7796698a2085ef3e7b13f9',
    messagingSenderId: '551175519868',
    projectId: 'my-first-firebase-efee1',
    storageBucket: 'my-first-firebase-efee1.appspot.com',
    iosClientId: '551175519868-4fkgllkoi6l1bte0rgpo28imaheh9ron.apps.googleusercontent.com',
    iosBundleId: 'com.example.ass07',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvAUoN7aOBhX9z582W6UL8KWYVm5RRY7s',
    appId: '1:551175519868:ios:7796698a2085ef3e7b13f9',
    messagingSenderId: '551175519868',
    projectId: 'my-first-firebase-efee1',
    storageBucket: 'my-first-firebase-efee1.appspot.com',
    iosClientId: '551175519868-4fkgllkoi6l1bte0rgpo28imaheh9ron.apps.googleusercontent.com',
    iosBundleId: 'com.example.ass07',
  );
}
